public class Colecoes {
// //? Em Apex, uma lista é uma coleção ordenada de elementos. Você pode adicionar, remover ou buscar elementos em uma lista por índice ou por valor.

// //? Declaração de uma lista de inteiros
// List<Integer> list = new List<Integer>();

// //? Adicionar elementos à lista
// list.add(1);
// list.add(2);
// list.add(3);

// //? Acessar um elemento da lista por índice
// Integer value = list[0];


// //? Um conjunto é uma coleção de elementos únicos, não ordenados. Você pode adicionar, remover ou verificar a existência de um elemento em um conjunto, mas não pode acessar um elemento pelo índice.

// //? Declaração de um conjunto de inteiros
// Set<Integer> set = new Set<Integer>();

// //? Adicionar elementos ao conjunto
// set.add(1);
// set.add(2);
// set.add(3);

// //? Verificar se o conjunto contém um elemento
// Boolean containsValue = set.contains(1);


// //? Um mapa é uma coleção de pares chave-valor. Você pode adicionar, remover ou buscar elementos em um mapa por chave. A chave é única e pode ser do tipo String ou do tipo qualquer tipo primitivo. O valor pode ser de qualquer tipo.

// //? Declaração de um mapa com chaves do tipo String e valores do tipo Integer
// Map<String, Integer> map = new Map<String, Integer>();

// //? Adicionar elementos ao mapa
// map.put('one', 1);
// map.put('two', 2);
// map.put('three', 3);

// //? Acessar um elemento do mapa por chave
// Integer mapValue = map.get('one');

   
}
